# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algopedia', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='algopedia.Language'),
            preserve_default=False,
        ),
    ]
