# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algopedia', '0003_implementation_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
            ],
        ),
        migrations.AddField(
            model_name='algo',
            name='category',
            field=models.ManyToManyField(to='algopedia.Category'),
        ),
    ]
