# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algopedia', '0005_auto_20151211_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algo',
            name='category',
            field=models.ManyToManyField(blank=True, to='algopedia.Category'),
        ),
    ]
