# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algopedia', '0009_star_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
