# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algopedia', '0012_notebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algo',
            name='category',
        ),
    ]
