# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        ('algopedia', '0015_delete_algo'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='algo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wiki.Article'),
            preserve_default=False,
        ),
    ]
