# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        ('algopedia', '0016_implementation_algo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='algo',
            field=models.ManyToManyField(related_name='category', to='wiki.Article'),
        ),
    ]
