# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algopedia', '0017_category_algo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='algo',
            new_name='algos',
        ),
    ]
