# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        ('algopedia', '0018_auto_20160119_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('wiki.article',),
        ),
        migrations.AlterField(
            model_name='category',
            name='algos',
            field=models.ManyToManyField(related_name='category', to='algopedia.Algo'),
        ),
    ]
